#!/usr/bin/env python3
"""Render FocusBro's ambient sounds from audio/recipe.json.

    python3 scripts/audio/build.py            # render everything into audio/dist/
    python3 scripts/audio/build.py rain fan   # render only these

Outputs (audio/dist/ is NOT committed — the files are served from R2):
  audio/dist/<name>.<sha10>.m4a   AAC-LC 48 kHz stereo, content-hashed name
  audio/manifest.json             what the app loads: file, loop points, bytes, sha256
  audio/SOURCES.md                provenance: one row per shipped file, regenerated
  public/index.html               the `// <audio-manifest>` block (SOUND_FILES)

Every loop is mastered the same way, and the reasons are the defects a listener
hears in cheap sound apps:
  * cut from the steadiest stretch of the recording (scripts/audio/measure.py
    finds it), so no single memorable event marks the repeat;
  * high-passed per source (wind rumble, handling noise, DC);
  * looped with an equal-power crossfade of the tail into the head (no click,
    no dip in level at the seam);
  * padded with one second of circular context on each side. The app loops
    between loopStart and loopEnd, so AAC encoder priming / end padding and the
    codec's boundary smearing land in audio that is never played — the seam is
    sample-continuous whatever the browser's decoder does with the edit list;
  * normalised to one integrated loudness (-23 LUFS, EBU R128), true peak held
    under -1 dBTP with a limiter run circularly (3x tiled, middle copy kept) so
    the limiter's own state is continuous across the seam.
"""
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request

import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
RECIPE = os.path.join(ROOT, 'audio', 'recipe.json')
DIST = os.path.join(ROOT, 'audio', 'dist')
MANIFEST = os.path.join(ROOT, 'audio', 'manifest.json')
SOURCES_MD = os.path.join(ROOT, 'audio', 'SOURCES.md')
INDEX_HTML = os.path.join(ROOT, 'public', 'index.html')
CACHE = os.environ.get('FOCUSBRO_AUDIO_CACHE', os.path.expanduser('~/.cache/focusbro-audio'))
UA = {'User-Agent': 'FocusBroAudioBuild/1.0 (https://focusbro.net)'}


# ── sources ───────────────────────────────────────────────────────────────
def md5(path):
    h = hashlib.md5()
    with open(path, 'rb') as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def fetch(src):
    """Local path of a source, downloading archive.org originals on first use."""
    if src['kind'] == 'archive.org':
        path = os.path.join(CACHE, 'archive', src['id'], src['file'])
        if not os.path.exists(path):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            url = f"https://archive.org/download/{src['id']}/{urllib.parse.quote(src['file'])}"
            print(f'  downloading {url}')
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=600) as r, open(path + '.part', 'wb') as fh:
                for chunk in iter(lambda: r.read(1 << 20), b''):
                    fh.write(chunk)
            os.rename(path + '.part', path)
        got = md5(path)
        if got != src['md5']:
            raise SystemExit(f"{path}: md5 {got} != recipe {src['md5']} — the archive file changed; re-audit before shipping")
        return path
    if src['kind'] == 'elevenlabs':
        path = os.path.join(CACHE, src['local'])
        if not os.path.exists(path):
            raise SystemExit(f"{path} missing. ElevenLabs takes cannot be regenerated byte-for-byte; fetch the archived take:\n"
                             f"  npx wrangler r2 object get focusbro-audio/{src['r2']} --file {path} --remote")
        return path
    raise SystemExit(f"unknown source kind {src['kind']}")


def decode(path, start, dur, filters, sr):
    """Float64 stereo [n, 2] of `dur` seconds from `start`, filtered. Filters run
    over up to 2 s of pre-roll that is then dropped, so a high-pass never puts
    its start-up transient into the material."""
    pre = min(2.0, float(start))
    af = f'aresample={sr}:filter_size=64:phase_shift=10:cutoff=0.97'
    if filters:
        af += ',' + filters
    cmd = ['ffmpeg', '-v', 'error', '-ss', str(start - pre), '-t', str(dur + pre), '-i', path,
           '-af', af, '-ac', '2', '-ar', str(sr), '-f', 'f32le', '-']
    raw = subprocess.run(cmd, capture_output=True, check=True).stdout
    x = np.frombuffer(raw, dtype=np.float32).reshape(-1, 2).astype(np.float64)
    x = x[int(round(pre * sr)):]
    n = int(round(dur * sr))
    if len(x) < n:
        raise SystemExit(f'{path}: asked for {dur}s from {start}s, got {len(x) / sr:.2f}s')
    return x[:n]


# ── loop construction ─────────────────────────────────────────────────────
def ramps(n):
    t = (np.arange(n) + 0.5) / n
    return np.sin(t * np.pi / 2)[:, None], np.cos(t * np.pi / 2)[:, None]   # fade-in, fade-out (equal power)


def join(a, b, seconds, sr):
    n = int(round(seconds * sr))
    fi, fo = ramps(n)
    return np.concatenate([a[:-n], a[-n:] * fo + b[:n] * fi, b[n:]])


def close_loop(x, seconds, sr):
    """x is L + n samples; return L samples whose end runs seamlessly into its start.
    The head is a crossfade from the tail's continuation (x[L:]) into x[:n]."""
    n = int(round(seconds * sr))
    if n == 0:
        return x
    L = len(x) - n
    fi, fo = ramps(n)
    out = x[:L].copy()
    out[:n] = x[:n] * fi + x[L:L + n] * fo
    return out


def circular(fn, loop):
    """Run a stateful process (filter, limiter) over the loop as if it never ended:
    tile 3x, process, keep the middle copy."""
    L = len(loop)
    return fn(np.concatenate([loop, loop, loop]))[L:2 * L]


# ── loudness ──────────────────────────────────────────────────────────────
def write_wav(path, x, sr, fmt='pcm_f32le'):
    data = np.ascontiguousarray(x, dtype=np.float32).tobytes()
    subprocess.run(['ffmpeg', '-v', 'error', '-y', '-f', 'f32le', '-ar', str(sr), '-ac', '2', '-i', '-',
                    '-c:a', fmt, path], input=data, check=True)


def ebur128(x, sr):
    """(integrated LUFS, true peak dBTP) via ffmpeg's EBU R128 meter."""
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, 'm.wav')
        write_wav(p, x, sr)
        err = subprocess.run(['ffmpeg', '-nostats', '-i', p, '-af', 'ebur128=peak=true', '-f', 'null', '-'],
                             capture_output=True, text=True).stderr
    summary = err[err.rfind('Summary:'):]
    lufs = float(re.search(r'I:\s+(-?[\d.]+|-inf) LUFS', summary).group(1))
    peak = float(re.search(r'Peak:\s+(-?[\d.]+|-inf) dBFS', summary).group(1))
    return lufs, peak


def ffmpeg_filter(x, sr, af):
    data = np.ascontiguousarray(x, dtype=np.float32).tobytes()
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-f', 'f32le', '-ar', str(sr), '-ac', '2', '-i', '-',
                          '-af', af, '-f', 'f32le', '-'], input=data, capture_output=True, check=True).stdout
    y = np.frombuffer(raw, dtype=np.float32).reshape(-1, 2).astype(np.float64)
    return y[:len(x)]


def normalise(loop, sr, target, max_tp, circular_proc=True):
    """Gain to `target` LUFS; if true peak then exceeds max_tp, a circular limiter.
    Returns (signal, notes)."""
    notes = []
    lufs, _ = ebur128(np.concatenate([loop, loop]), sr)
    gain_db = target - lufs
    y = loop * 10 ** (gain_db / 20)
    notes.append(f'gain {gain_db:+.1f} dB (from {lufs:.1f} LUFS)')
    _, tp = ebur128(np.concatenate([y, y]), sr)
    if tp > max_tp - 1.0:
        lim = 10 ** ((max_tp - 2.0) / 20)
        af = f'alimiter=limit={lim:.4f}:attack=1:release=20:level=false:latency=true'
        before = y
        y = circular(lambda z: ffmpeg_filter(z, sr, af), y) if circular_proc else ffmpeg_filter(y, sr, af)
        lufs2, tp2 = ebur128(np.concatenate([y, y]), sr)
        y = y * 10 ** ((target - lufs2) / 20)
        # how much of the sound did the limiter actually touch? (10 ms windows
        # whose level dropped more than 1 dB relative to the overall gain change)
        w = 480 * (sr // 48000)
        n = len(y) // w * w
        rb = np.sqrt(np.mean(before[:n].reshape(-1, w, 2) ** 2, axis=(1, 2)) + 1e-20)
        ra = np.sqrt(np.mean(y[:n].reshape(-1, w, 2) ** 2, axis=(1, 2)) + 1e-20)
        d = 20 * np.log10(ra / rb)
        touched = np.mean(d < np.median(d) - 1.0) * 100
        notes.append(f'circular peak limiter at {max_tp - 2.0:.1f} dBFS (true peak was {tp:.1f} dBTP; '
                     f'{touched:.2f}% of 10 ms windows reduced by >1 dB)')
    return y, notes


# ── synthesis ─────────────────────────────────────────────────────────────
def synth_drone(seconds, sr, seed=7):
    """A warm open-fifth drone that is EXACTLY periodic over `seconds`: every
    partial, detune and modulator is an integer number of cycles per loop, so the
    loop has no seam at all. Each partial is a pair of copies a few hundredths of
    a hertz apart (slow beating, the 'breathing'), panned apart, with slow
    per-voice swells and a shared brightness swell above 600 Hz."""
    rng = np.random.default_rng(seed)
    n = int(seconds * sr)
    t = np.arange(n) / sr
    df = 1.0 / seconds
    q = lambda f: round(f / df) * df            # snap to the loop's frequency grid
    out = np.zeros((n, 2))

    def drift():
        """A smooth random curve in [0, 1], periodic over the loop and over nothing
        shorter: a random Fourier series on harmonics 1..5 of the loop rate. A plain
        LFO at 2 cycles per loop would make the loop recur at half its length."""
        c = sum(rng.normal() / k * np.sin(2 * np.pi * k * df * t + rng.uniform(0, 2 * np.pi)) for k in range(1, 6))
        return (c - c.min()) / (c.max() - c.min())

    bright = drift()                                                      # shared brightness
    voices = [(55.0, 1.0), (82.5, 0.55), (110.0, 0.5), (165.0, 0.3), (220.0, 0.2), (330.0, 0.08)]
    for vi, (f0, vg) in enumerate(voices):
        swell = 0.75 + 0.25 * drift()
        k = 1
        while k * f0 <= 2600:
            f = k * f0
            amp = vg / k ** 1.7
            if f > 600:
                amp_t = amp * (0.35 + 0.65 * bright)
            else:
                amp_t = amp
            for side, pan in ((-1, 0.3), (1, 0.7)):
                fk = q(f + side * rng.integers(1, 4) * df * (1 + k / 6))
                ph = rng.uniform(0, 2 * np.pi)
                s = np.sin(2 * np.pi * fk * t + ph) * amp_t * swell
                out[:, 0] += s * np.cos(pan * np.pi / 2)
                out[:, 1] += s * np.sin(pan * np.pi / 2)
            k += 1
    # air: periodic band-limited noise (random-phase spectrum on the loop's own
    # frequency grid is periodic by construction), riding the brightness swell
    spec = np.zeros(n // 2 + 1, dtype=complex)
    freqs = np.fft.rfftfreq(n, 1 / sr)
    band = (freqs > 250) & (freqs < 2500)
    for ch in range(2):
        spec[:] = 0
        spec[band] = (1 / np.sqrt(freqs[band])) * np.exp(1j * rng.uniform(0, 2 * np.pi, band.sum()))
        air = np.fft.irfft(spec, n)
        air /= np.sqrt(np.mean(air ** 2)) + 1e-12
        out[:, ch] += air * 0.012 * (0.4 + 0.6 * bright)
    return out


# ── rendering ─────────────────────────────────────────────────────────────
def render_loop(name, spec, recipe, sr):
    notes = []
    parts = []
    for seg in spec['segments']:
        src = recipe['sources'][seg['src']]
        parts.append(decode(fetch(src), seg['start'], seg['dur'], spec.get('filters'), sr))
        notes.append(f"{seg['src']} {seg['start']}–{seg['start'] + seg['dur']} s")
    x = parts[0]
    for p in parts[1:]:
        x = join(x, p, spec['join_xfade'], sr)
    if len(parts) > 1:
        notes.append(f"takes joined with {spec['join_xfade']} s equal-power crossfades")
    if spec.get('palindrome'):
        loop = np.concatenate([x, x[::-1]])
        notes.append('palindrome loop (forward then reversed): sample-continuous at both turns, doubles the period')
    else:
        loop = close_loop(x, spec['xfade'], sr)
        notes.append(f"seam: {spec['xfade']} s equal-power crossfade of tail into head")
    if spec.get('filters'):
        notes.append(f"filters: {spec['filters']}")
    loop = loop - loop.mean(axis=0)
    return loop, notes


def render_drone(spec, recipe, sr):
    loop = synth_drone(spec['seconds'], sr)
    return loop, [f"synthesised, exactly periodic over {spec['seconds']} s (no crossfade needed)"]


def render_strikes(name, spec, recipe, sr):
    """Bowl: individual strikes in fixed slots; the app schedules them at random
    gaps, so the texture never repeats. Each strike is levelled to the same
    loudness; then the whole set is scaled so a texture of one strike every
    `texture_interval` s meets the loudness target like every other sound."""
    slots, at, notes = [], 0.0, []
    lead, tail = 0.25, 0.25
    strikes = []
    for st in spec['strikes']:
        src = recipe['sources'][st['src']]
        path = fetch(src)
        x = decode(path, 0, float(subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of',
                                                  'csv=p=0', path], capture_output=True, text=True).stdout) - 0.05,
                   spec.get('filters'), sr)
        env = np.abs(x).max(axis=1)
        onset = int(np.argmax(env > 0.05 * env.max()))
        onset = max(0, onset - int(0.005 * sr))
        n = int(st['dur'] * sr)
        s = x[onset:onset + n]
        if len(s) < n:
            s = np.concatenate([s, np.zeros((n - len(s), 2))])
        fo = int(3 * sr)
        s[-fo:] *= np.cos(np.linspace(0, np.pi / 2, fo))[:, None] ** 2
        lufs, _ = ebur128(s[: int(6 * sr)], sr)
        s *= 10 ** ((-23 - lufs) / 20)
        strikes.append(s)
        notes.append(f"{st['src']}: onset at {onset / sr:.2f} s, {st['dur']} s kept, 3 s fade-out, levelled")
    body = []
    for s in strikes:
        body += [np.zeros((int(lead * sr), 2)), s, np.zeros((int(tail * sr), 2))]
        slots.append({'at': round(at, 6), 'dur': round(lead + len(s) / sr + tail, 6)})
        at += lead + len(s) / sr + tail
    signal = np.concatenate(body)
    # the texture as the app plays it, to set the shared gain
    iv = int(spec['texture_interval'] * sr)
    tex = np.zeros((iv * 12 + len(strikes[0]), 2))
    for i in range(12):
        s = strikes[i % len(strikes)]
        tex[i * iv:i * iv + len(s)] += s
    lufs, _ = ebur128(tex, sr)
    g = 10 ** ((recipe['target_lufs'] - lufs) / 20)
    signal *= g
    notes.append(f"set gain {20 * np.log10(g):+.1f} dB so a strike every {spec['texture_interval']} s measures {recipe['target_lufs']} LUFS")
    _, tp = ebur128(signal, sr)
    if tp > recipe['max_true_peak_dbtp'] - 0.5:
        signal *= 10 ** ((recipe['max_true_peak_dbtp'] - 0.5 - tp) / 20)
        notes.append('peak-limited by gain to hold true peak')
    return signal, slots, notes


def encode(name, signal, sr, bitrate):
    os.makedirs(DIST, exist_ok=True)
    with tempfile.TemporaryDirectory() as d:
        wav = os.path.join(d, 'master.wav')
        m4a = os.path.join(d, 'out.m4a')
        write_wav(wav, signal, sr, fmt='pcm_s24le')
        subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', wav, '-c:a', 'aac', '-b:a', bitrate, '-ar', str(sr),
                        '-movflags', '+faststart', '-map_metadata', '-1', '-fflags', '+bitexact',
                        '-flags:a', '+bitexact', m4a], check=True)
        data = open(m4a, 'rb').read()
    sha = hashlib.sha256(data).hexdigest()
    fname = f'{name}.{sha[:10]}.m4a'
    for old in os.listdir(DIST):
        if old.startswith(name + '.') and old.endswith('.m4a') and old != fname:
            os.remove(os.path.join(DIST, old))
    with open(os.path.join(DIST, fname), 'wb') as fh:
        fh.write(data)
    return fname, sha, len(data)


def main():
    recipe = json.load(open(RECIPE))
    sr = recipe['sample_rate']
    pad = recipe['pad_seconds']
    only = set(sys.argv[1:])
    manifest = json.load(open(MANIFEST)) if os.path.exists(MANIFEST) else {'sounds': {}}
    notes_all = manifest.get('_notes', {})
    for name, spec in recipe['sounds'].items():
        if only and name not in only:
            continue
        print(f'[{name}]')
        if 'strikes' in spec:
            signal, slots, notes = render_strikes(name, spec, recipe, sr)
            fname, sha, size = encode(name, signal, sr, recipe['aac_bitrate'])
            entry = {'file': fname, 'kind': 'strikes', 'strikes': slots, 'bytes': size, 'sha256': sha}
            srcs = [st['src'] for st in spec['strikes']]
        else:
            if 'synth' in spec:
                loop, notes = render_drone(spec, recipe, sr)
                srcs = [spec['src']]
            else:
                loop, notes = render_loop(name, spec, recipe, sr)
                srcs = [s['src'] for s in spec['segments']]
            loop, nn = normalise(loop, sr, recipe['target_lufs'], recipe['max_true_peak_dbtp'])
            notes += nn
            P = int(pad * sr)
            padded = np.concatenate([loop[-P:], loop, loop[:P]])
            fname, sha, size = encode(name, padded, sr, recipe['aac_bitrate'])
            entry = {'file': fname, 'kind': 'loop', 'loopStart': pad, 'loopEnd': round(pad + len(loop) / sr, 6),
                     'bytes': size, 'sha256': sha}
            notes.append(f'{pad} s circular pad each side; app loops [{pad}, {entry["loopEnd"]}] s')
        entry['sources'] = srcs
        manifest['sounds'][name] = entry
        notes_all[name] = notes + [f"AAC-LC {recipe['aac_bitrate']}, {sr} Hz stereo (.m4a)"]
        print(f'  -> {fname} ({size / 1e6:.2f} MB)')
        for n in notes:
            print('    ' + n)
    manifest['_notes'] = notes_all
    manifest['sounds'] = dict(sorted(manifest['sounds'].items()))
    manifest['version'] = recipe['version']
    manifest['target_lufs'] = recipe['target_lufs']
    with open(MANIFEST, 'w') as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write('\n')
    write_sources_md(recipe, manifest)
    patch_index(manifest)


def write_sources_md(recipe, manifest):
    L = ['# Ambient audio — sources and provenance', '',
         '> Generated by `scripts/audio/build.py` from `audio/recipe.json`. Do not edit by hand.',
         '> Every file the app can play has a row here; `api/src/__tests__/sound-catalog.test.js` fails the build otherwise.', '',
         f"Loudness target {recipe['target_lufs']} LUFS integrated (EBU R128), true peak ≤ {recipe['max_true_peak_dbtp']} dBTP. "
         f"Retrieved {recipe['retrieved']}. Field recordings are re-downloaded from archive.org by the build and checked against the md5 below.", '',
         '## Licences in one paragraph', '',
         'The field recordings come from **radio aporee ::: maps**, where each recordist chooses the licence at upload and may choose '
         '"PUBLIC DOMAIN" (aporee.org/maps/info: *"select a licence under which the recording should be published, or choose PUBLIC DOMAIN"*). '
         'Every recording used here is one its recordist dedicated to the public domain; the Internet Archive mirror records that choice as '
         'Creative Commons Public Domain Mark 1.0 in the item\'s `licenseurl`. No attribution is required — it is given anyway. '
         'Keys, Fan and the Bowl strikes were generated with ElevenLabs Sound Effects on a paid plan (commercial use permitted); the takes are archived in R2 '
         'under `sources/elevenlabs/` because a generation cannot be repeated byte-for-byte. The Drone is our own synthesis (CC0). '
         'The three "hush" noises are synthesised in the browser and ship no file.', '']
    L += ['## Files', '', '| Sound | File | Source | Author | Licence | Processing |', '|---|---|---|---|---|---|']
    for name, e in manifest['sounds'].items():
        srcs = [recipe['sources'][s] for s in e['sources']]
        src_cell = '<br>'.join(
            f"[{s['id']}]({s['page']}) — {s['title']} (md5 `{s['md5']}`)" if s['kind'] == 'archive.org'
            else (f"ElevenLabs take `{s['r2']}` — prompt: “{s['prompt']}” ({s['params']})" if s['kind'] == 'elevenlabs'
                  else s['script']) for s in srcs)
        authors = '<br>'.join(sorted({s['author'] for s in srcs}))
        lic = '<br>'.join(sorted({f"[{s['license']}]({s['license_url']})" for s in srcs}))
        proc = '; '.join(manifest['_notes'][name])
        L.append(f"| {recipe['sounds'][name]['label']} (`{name}`) | `{e['file']}`<br>sha256 `{e['sha256'][:16]}…` · {e['bytes'] / 1e6:.2f} MB "
                 f"| {src_cell} | {authors} | {lic} | {proc} |")
    L += ['', '## Not shipped as files', '',
          '| Sound | How |', '|---|---|',
          '| Deep hush (`brown`), Soft hush (`pink`), Bright hush (`white`) | Synthesised in the browser (`noiseBuffer` in `public/index.html`): one 60 s buffer per colour whose tail is crossfaded into its head, so the loop has no step. Noise is noise; a file would add bytes and nothing else. |', '']
    with open(SOURCES_MD, 'w') as fh:
        fh.write('\n'.join(L))


def patch_index(manifest):
    html = open(INDEX_HTML).read()
    files = {}
    for name, e in manifest['sounds'].items():
        if e['kind'] == 'loop':
            files[name] = {'file': e['file'], 'loopStart': e['loopStart'], 'loopEnd': e['loopEnd'], 'bytes': e['bytes']}
        else:
            files[name] = {'file': e['file'], 'strikes': e['strikes'], 'bytes': e['bytes']}
    block = ('// <audio-manifest> — generated by scripts/audio/build.py from audio/manifest.json; do not edit by hand\n'
             'const SOUND_FILES = ' + json.dumps(files, separators=(',', ':')) + ';\n'
             '// </audio-manifest>')
    new, n = re.subn(r'// <audio-manifest>.*?// </audio-manifest>', lambda m: block, html, flags=re.S)
    if n != 1:
        print('  (index.html has no // <audio-manifest> block yet — not patched)')
        return
    if new != html:
        open(INDEX_HTML, 'w').write(new)
        print('  patched public/index.html SOUND_FILES')


if __name__ == '__main__':
    main()
