#!/usr/bin/env bash
# Upload the built sounds (and the ElevenLabs takes they came from) to R2.
#   CLOUDFLARE_API_TOKEN=… CLOUDFLARE_ACCOUNT_ID=… bash scripts/audio/upload.sh
# Names are content-hashed, so re-running is safe: an existing name already
# holds exactly these bytes. Old names are left in place — a page still cached
# with the previous manifest must keep working.
set -euo pipefail
cd "$(dirname "$0")/../.."
WRANGLER="${WRANGLER:-npx --prefix api wrangler}"
CACHE="${FOCUSBRO_AUDIO_CACHE:-$HOME/.cache/focusbro-audio}"
for f in audio/dist/*.m4a; do
  $WRANGLER r2 object put "focusbro-audio/$(basename "$f")" --file "$f" --remote \
    --content-type audio/mp4 --cache-control "public, max-age=31536000, immutable"
done
# provenance: the generated takes cannot be regenerated byte-for-byte
python3 - "$CACHE" <<'EOF' | while read -r key local; do
import json, sys
r = json.load(open('audio/recipe.json'))
for s in r['sources'].values():
    if s['kind'] == 'elevenlabs':
        print(s['r2'], sys.argv[1] + '/' + s['local'])
EOF
  $WRANGLER r2 object put "focusbro-audio/$key" --file "$local" --remote --content-type audio/mpeg
done
